# Generated by Django 4.1.3 on 2022-11-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Details',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_head_branch', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Bank_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('dist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dist_name', models.CharField(max_length=100)),
                ('dist_code', models.IntegerField()),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dist_id', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('sup_id', models.IntegerField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'supervisor',
                'managed': False,
            },
        ),
    ]
