# Generated by Django 4.1.3 on 2022-11-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='labourer_db.district',
        ),
    ]
