# Generated by Django 4.1.3 on 2022-11-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour_management_system', '0002_alter_district_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
    ]
