# Generated by Django 4.1.3 on 2022-11-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour_management_system', '0003_alter_district_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bank_details',
            table='labourer_db"."Bank_details',
        ),
        migrations.AlterModelTable(
            name='district',
            table='labourer_db"."district',
        ),
        migrations.AlterModelTable(
            name='person',
            table='labourer_db"."person',
        ),
        migrations.AlterModelTable(
            name='supervisor',
            table='labourer_db"."supervisor',
        ),
    ]
